CC=gcc
CFLAGS=-Wall -g
FNAME1=fi_0
FNAME2=fi_1
FNAME3=fi_2

all:
	$(CC) $(CFLAGS) -o $(FNAME1).out $(FNAME1).c
	$(CC) $(CFLAGS) -o $(FNAME2).out $(FNAME2).c
	$(CC) $(CFLAGS) -o $(FNAME3).out $(FNAME3).c

clear:
	rm *.out
