CC=gcc
CFLAGS=-Wall -g
FI=fi_0.c fi_1.c fi_2.c fi.h

all:
	$(CC) $(CFLAGS) -o $(FNAME1).out $(FNAME1).c
	$(CC) $(CFLAGS) -o $(FNAME2).out $(FNAME2).c
	$(CC) $(CFLAGS) -o $(FNAME3).out $(FNAME3).c

clean:
	rm -f *.out *.bin
